spring:
  profile.active: prod
  datasource:
  url: ${DB_URL}${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  jpa:
    jpa:
      show-sql: false
      hibernate:
        format_sql: false
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  error:
    include-stacktrace: never
    ddl-auto: update
api:
  security:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
